
CREATE DATABASE GUARDIANS;

CREATE TABLE JOGO(
IDJOGO INT PRIMARY KEY AUTO_INCREMENT,	
JOGO VARCHAR(50) NOT NULL,
DATA DATE
);

CREATE TABLE JGDEV(
ID_JOGO INT,
ID_DEV INT,

FOREIGN KEY(ID_JOGO)
	REFERENCES JOGO(IDJOGO),
	FOREIGN KEY(ID_DEV)
	REFERENCES DEVELOPER(IDDEV));

CREATE TABLE DEVELOPER(
IDDEV INT PRIMARY KEY AUTO_INCREMENT,
DEV VARCHAR(50) NOT NULL,
DEVDATA DATE
)

CREATE TABLE JGPUBLI(
ID_JOGO INT,
ID_PUBLI INT,

FOREIGN KEY(ID_JOGO)
	REFERENCES JOGO(IDJOGO),
	FOREIGN KEY(ID_PUBLI)
	REFERENCES PUBLISHER(IDPUBLI)
);

CREATE TABLE PUBLISHER(
IDPUBLI INT PRIMARY KEY AUTO_INCREMENT,
PUBLISHER VARCHAR(50) NOT NULL,
PUBLIDATE DATE  );

CREATE TABLE JGPLAT(
ID_JOGO INT,
ID_PLATNOME INT,

FOREIGN KEY(ID_JOGO)
	REFERENCES JOGO(IDJOGO),
	FOREIGN KEY(ID_PLATNOME)
	REFERENCES PLATAFORMAS(IDPLATNOME));

CREATE TABLE PLATAFORMAS(
IDPLATNOME INT PRIMARY KEY AUTO_INCREMENT,	
PLATNOME VARCHAR(50) NOT NULL,
FABRICANTE VARCHAR(50),
GERACAO CHAR(1),
PLATDATA DATE);